/*
 * gen_xor_header.c — XOR Encoder for Payload Embedding
 * ============================================================================
 * This helper is run during the Makefile build. It:
 *   1. Reads the compiled `payload_elf` binary from stdin.
 *   2. XOR-encodes it with a hardcoded 1-byte key.
 *   3. Outputs a C header file (`payload_blob.h`) containing the
 *      encoded byte array so it can be embedded in `loader.c`.
 *
 * Research relevance (MITRE T1027.002 — Software Packing):
 *   XOR encoding ensures the ELF magic bytes (0x7F 'E' 'L' 'F') are
 *   NOT present in the loader binary. This demonstrates why `file`,
 *   `strings`, and simple signature scanners fail to detect the
 *   embedded payload — a core contribution of this research.
 *
 * Usage (via Makefile):
 *   ./gen_xor_header < payload_elf > payload_blob.h
 *
 * WARNING: FOR ACADEMIC/RESEARCH USE ONLY INSIDE AN ISOLATED VM.
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

/* XOR key — deliberately simple (single-byte) to stay in scope of PoC.
 * Real-world malware uses multi-byte RC4/AES (e.g., Ezuri uses AES-256-CTR). */
#define XOR_KEY 0xAB

int main(void) {
    uint8_t *buf = NULL;
    size_t   len = 0;
    size_t   cap = 4096;
    int      c;

    buf = malloc(cap);
    if (!buf) { 
        perror("malloc"); return 1; 
    }

    /* Read entire payload into buffer */
    while ((c = getchar()) != EOF) {
        if (len >= cap) {
            cap *= 2;
            /* B1 fix: use tmp so original buf is preserved on failure */
            uint8_t *tmp = realloc(buf, cap);
            if (!tmp) { perror("realloc"); free(buf); return 1; }
            buf = tmp;
        }
        buf[len++] = (uint8_t)c;
    }

    /* Emit a self-documenting C header */
    printf("/*\n");
    printf(" * payload_blob.h — AUTO-GENERATED by gen_xor_header.c\n");
    printf(" * DO NOT EDIT BY HAND.\n");
    printf(" *\n");
    printf(" * XOR key : 0x%02X\n", XOR_KEY);
    printf(" * Original size : %zu bytes\n", len);
    printf(" * ELF magic BEFORE encoding : 7f 45 4c 46 (\"\\x7fELF\")\n");
    printf(" * ELF magic AFTER  encoding : %02x %02x %02x %02x\n",
           (uint8_t)(0x7f ^ XOR_KEY),
           (uint8_t)('E'  ^ XOR_KEY),
           (uint8_t)('L'  ^ XOR_KEY),
           (uint8_t)('F'  ^ XOR_KEY));
    printf(" *\n");
    printf(" * Research note: The transformed magic bytes prove that a\n");
    printf(" * simple `file` or `strings` scan on `loader` cannot identify\n");
    printf(" * the embedded ELF — supporting the Scanner Gap hypothesis.\n");
    printf(" */\n\n");
    printf("#ifndef PAYLOAD_BLOB_H\n");
    printf("#define PAYLOAD_BLOB_H\n\n");
    printf("#define PAYLOAD_XOR_KEY  0x%02X\n", XOR_KEY);
    printf("#define PAYLOAD_SIZE     %zu\n\n", len);
    printf("static const unsigned char payload_blob[PAYLOAD_SIZE] = {\n");

    for (size_t i = 0; i < len; i++) {
        uint8_t encoded = buf[i] ^ XOR_KEY;
        if (i % 12 == 0) printf("    ");
        printf("0x%02x", encoded);
        if (i + 1 < len) printf(", ");
        if ((i + 1) % 12 == 0) printf("\n");
    }

    printf("\n};\n\n");
    printf("#endif /* PAYLOAD_BLOB_H */\n");

    free(buf);
    return 0;
}
